version: "2"
plugins:
  tslint:
    enabled: true
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
        - typescript
exclude_patterns:
- ".circleci/**/*"
- "bin/*"
- "cypress/**/*"
- "samples/**/*"
- "testReports/**/*"