name: Publish and release cypress-slack-reporter-old

on:
  repository_dispatch:
    types:
      - release-triggered
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  ENV_SUT: ${{ secrets.ENV_SUT }}
  CI_PROVIDER_TO_TEST: 'github'

defaults:
  run:
    working-directory: cypress-slack-reporter-old

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: cypress-slack-reporter-old/yarn.lock
      - id: publish
        run: scripts/ci/release.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTOMATION_TOKEN}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.publish.outputs.version }}
          release_name: Release v${{ steps.publish.outputs.version }}
          body: ${{steps.publish.outputs.notes}}
          draft: false
          prerelease: false
